AWSTemplateFormatVersion: 2010-09-09
Description: CFT MAnaged via stackset in Payer account. Baseline IAM resources for a new Novawell account 
Resources:
  NVWAWSCrossAccountRam:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT MAnaged via stackset in Payer account. Allows permissions for resource access manager for cross account data sharing
      ManagedPolicyName: NVW_AWS_CrossAccountData_Ram
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:    
              - "ram:ListPermissionVersions"
              - "ram:AcceptResourceShareInvitation"
              - "ram:EnableSharingWithAwsOrganization"
              - "ram:GetResourceShareAssociations"
              - "ram:GetResourcePolicies"
              - "ram:GetResourceShareInvitations"
              - "ram:AssociateResourceSharePermission"
              - "ram:ListResources"
              - "ram:GetPermission"
              - "ram:ListResourceSharePermissions"
              - "ram:ListPermissions"
              - "ram:GetResourceShares"
              - "ram:RejectResourceShareInvitation"
              - "ram:ListPrincipals"
              - "ram:ListResourceTypes"
              - "ec2:DescribeAvailabilityZones"
              - "ram:ListPendingInvitationResources"
              - "ram:DeleteResourceShare" 
            Resource: '*'                
  NVWAWSSQLWorkbench:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT MAnaged via stackset in Payer account. Developer Access to SQLWorkbench with no resource constraints 
      ManagedPolicyName: NVW_AWS_Developer_SQLWorkbench
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sqlworkbench:AssociateConnectionWithChart
              - sqlworkbench:AssociateConnectionWithTab
              - sqlworkbench:AssociateQueryWithTab
              - sqlworkbench:BatchDeleteFolder
              - sqlworkbench:BatchGetNotebookCell
              - sqlworkbench:CreateAccount
              - sqlworkbench:CreateChart
              - sqlworkbench:CreateConnection
              - sqlworkbench:CreateFolder
              - sqlworkbench:CreateNotebookCell
              - sqlworkbench:CreateNotebook
              - sqlworkbench:CreateNotebookFromVersion
              - sqlworkbench:CreateNotebookVersion
              - sqlworkbench:CreateSavedQuery
              - sqlworkbench:DeleteChart
              - sqlworkbench:DeleteConnection
              - sqlworkbench:DeleteNotebook
              - sqlworkbench:DeleteNotebookCell
              - sqlworkbench:DeleteNotebookVersion
              - sqlworkbench:DeleteSavedQuery
              - sqlworkbench:DeleteTab
              - sqlworkbench:DriverExecute
              - sqlworkbench:DuplicateNotebook
              - sqlworkbench:ExportNotebook
              - sqlworkbench:GenerateSession
              - sqlworkbench:GetAccountInfo
              - sqlworkbench:GetAccountSettings
              - sqlworkbench:GetAutocompletionMetadata
              - sqlworkbench:GetAutocompletionResource
              - sqlworkbench:GetChart
              - sqlworkbench:GetConnection
              - sqlworkbench:GetNotebook
              - sqlworkbench:GetNotebookVersion
              - sqlworkbench:GetQueryExecutionHistory
              - sqlworkbench:GetSavedQuery
              - sqlworkbench:GetUserInfo
              - sqlworkbench:GetUserWorkspaceSettings
              - sqlworkbench:ImportNotebook
              - sqlworkbench:ListConnections
              - sqlworkbench:ListDatabases
              - sqlworkbench:ListFiles
              - sqlworkbench:ListNotebookVersions
              - sqlworkbench:ListNotebooks
              - sqlworkbench:ListRedshiftClusters
              - sqlworkbench:ListQueryExecutionHistory
              - sqlworkbench:ListSampleDatabases
              - sqlworkbench:ListSavedQueryVersions
              - sqlworkbench:ListTabs
              - sqlworkbench:ListTagsForResource
              - sqlworkbench:ListTaggedResources
              - sqlworkbench:PutTab
              - sqlworkbench:PutUserWorkspaceSettings
              - sqlworkbench:RestoreNotebookVersion
              - sqlworkbench:TagResource
              - sqlworkbench:UpdateAccountExportSettings
              - sqlworkbench:UpdateAccountConnectionSettings
              - sqlworkbench:UpdateAccountGeneralSettings
              - sqlworkbench:UpdateChart
              - sqlworkbench:UpdateConnection
              - sqlworkbench:UpdateFileFolder
              - sqlworkbench:UpdateSavedQuery
              - sqlworkbench:UpdateNotebook
              - sqlworkbench:UpdateNotebookCellContent
              - sqlworkbench:UpdateNotebookCellLayout
              - sqlworkbench:UpdateFolder
              - sqlworkbench:UntagResource
            Resource: '*'       
  NVWAWSDeveloperspecific:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT MAnaged via stackset in Payer account. Developer Access to services with resource constraints
      ManagedPolicyName: NVW_AWS_Developer_Specific
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:CreateBackup
          - dynamodb:CreateGlobalTable
          - dynamodb:CreateTable
          - dynamodb:DeleteBackup
          - dynamodb:DeleteItem
          - dynamodb:DeleteTable
          - dynamodb:DescribeBackup
          - dynamodb:DescribeContinuousBackups
          - dynamodb:DescribeStream
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:PutItem
          - dynamodb:Query
          - dynamodb:RestoreTableFromBackup
          - dynamodb:RestoreTableToPointInTime
          - dynamodb:Scan
          - dynamodb:UpdateContinuousBackups
          - dynamodb:UpdateGlobalTable
          - dynamodb:UpdateGlobalTableSettings
          - dynamodb:UpdateItem
          - dynamodb:UpdateTable
          - dynamodb:UpdateTimeToLive
          Resource:
          - arn:aws:dynamodb:*:*:table/*/index/*
          - arn:aws:dynamodb:*:*:table/*/stream/*
          - arn:aws:dynamodb:*:*:table/*/backup/*
          - arn:aws:dynamodb::*:global-table/*
        - Action: pi:*
          Effect: Allow
          Resource: arn:aws:pi:*:*:metrics/rds/*   
  NVWAWSIAMReadOnly:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT MAnaged via stackset in Payer account. IAM ReadOnly Access w/ Passrole
      ManagedPolicyName: NVW_AWS_IAM_ReadOnly
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - iam:GenerateCredentialReport
          - iam:GenerateServiceLastAccessedDetails
          - iam:Get*
          - iam:List*
          - iam:PassRole
          - iam:SimulateCustomPolicy
          - iam:SimulatePrincipalPolicy
          Resource: "*"      
  NVWAWSConsoleSuperUserPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT MAnaged via stackset in Payer account. Allows permissions for NVW_AWS_Console_SuperUser
      ManagedPolicyName: NVW_AWS_Console_SuperUser_Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:    
              - ssm:*
              - fsx:*
              - ds:*
              - iam:CreateRole
              - iam:CreateServiceLinkedRole
              - sns:*
              - cloudtrail:*
            Resource: '*'             
