AWSTemplateFormatVersion: 2010-09-09
Description: CFT MAnaged via stackset in Payer account. Baseline IAM resources for a new Novawell account 
Resources:
  NVWAWSConsoleSuperUserPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT MAnaged via stackset in Payer account. Allows permissions for NVW_AWS_Console_SuperUser
      ManagedPolicyName: NVW_AWS_Console_SuperUser_Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:    
              - ssm:*
              - fsx:*
              - ds:*
              - iam:CreateRole
              - iam:CreateServiceLinkedRole
              - sns:*
              - cloudtrail:*
            Resource: '*'             
