Type: AWS::CloudTrail::Trail
Properties:
  AdvancedEventSelectors: 
    - AdvancedEventSelector
  CloudWatchLogsLogGroupArn: String
  CloudWatchLogsRoleArn: String
  EnableLogFileValidation: Boolean
  EventSelectors: 
    - EventSelector
  IncludeGlobalServiceEvents: Boolean
  InsightSelectors: 
    - InsightSelector
  IsLogging: Boolean
  IsMultiRegionTrail: Boolean
  IsOrganizationTrail: Boolean
  KMSKeyId: String
  S3BucketName: String
  S3KeyPrefix: String
  SnsTopicName: String
  Tags: 
    - Tag
  TrailName: String