AWSTemplateFormatVersion: 2010-09-09
Description: CFT MAnaged via stackset in Payer account. Baseline IAM resources for a new Novawell account 
Resources:
  NVWAWSIAMReadOnly:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT MAnaged via stackset in Payer account. IAM ReadOnly Access w/ Passrole
      ManagedPolicyName: NVW_AWS_IAM_ReadOnly
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - iam:GenerateCredentialReport
          - iam:GenerateServiceLastAccessedDetails
          - iam:Get*
          - iam:List*
          - iam:PassRole
          - iam:SimulateCustomPolicy
          - iam:SimulatePrincipalPolicy
          Resource: "*"      
  NVWAWSConsoleSuperUserPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT MAnaged via stackset in Payer account. Allows permissions for NVW_AWS_Console_SuperUser
      ManagedPolicyName: NVW_AWS_Console_SuperUser_Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:    
              - ssm:*
              - fsx:*
              - ds:*
              - iam:CreateRole
              - iam:CreateServiceLinkedRole
              - sns:*
              - cloudtrail:*
            Resource: '*'             
  NVWAWSConsoleReadOnly:
    Type: "AWS::IAM::Role"
    Properties: 
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"
      AssumeRolePolicyDocument: 
        Statement: 
        - Effect: Allow
          Principal:
            AWS: "arn:aws:iam::782930490923:role/NVW_AWS_Console_ReadOnly"
          Action: 
            - "sts:AssumeRole"
            - "sts:TagSession"
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/cleardata-boundary'
      RoleName: "NVW_AWS_Console_ReadOnly"
  NVWAWSAdmins:
    Type: "AWS::IAM::Role"
    Properties: 
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      AssumeRolePolicyDocument: 
        Statement: 
        - Effect: Allow
          Principal:
            AWS: 
            - arn:aws:iam::782930490923:role/NVW_AWS_Console_Administrator
          Action:
            - "sts:AssumeRole" 
            - "sts:TagSession"                                  
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/cleardata-boundary'
      RoleName: "NVW_AWS_Console_Administrator"      
  NVWAWSConsoleSuperUser:
    Type: "AWS::IAM::Role"
    Properties: 
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/cleardata/customer/DPHI-Policy-SuperUser-1"
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/NVW_AWS_IAM_ReadOnly" 
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/NVW_AWS_Console_SuperUser_Policy"                  
        - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
        - "arn:aws:iam::aws:policy/AmazonRDSFullAccess"       
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AWSConfigUserAccess"          
        - "arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser"                                   
      AssumeRolePolicyDocument: 
        Statement: 
        - Effect: Allow
          Principal:
            AWS:
            - arn:aws:iam::782930490923:role/NVW_AWS_Console_SuperUser             
          Action: 
            - "sts:AssumeRole"  
            - "sts:TagSession"
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/cleardata-boundary'
      RoleName: "NVW_AWS_Console_SuperUser"   
    DependsOn: 
      - NVWAWSIAMReadOnly
      - NVWAWSConsoleSuperUserPolicy                      

