AWSTemplateFormatVersion: 2010-09-09
Description: NVW_AWS_UAT role for Novawell dev and uat accounts assumed from identity account managed by CFT
Resources:
  NVWAWSUATGeneric:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CFT managed via stackset in payer account. Provides UAT Access to services with no resource constraints 
      ManagedPolicyName: NVW_AWS_UAT_policy_generic 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - athena:Get*
              - athena:List*
              - athena:startqueryexecution
              - athena:stopqueryexecution
              - Cloudwatch:*
              - glue:*
              - kms:Decrypt
              - kms:Describe*
              - kms:List*
              - lakeformation:Get*
              - lakeformation:List*
              - lambda:*
              - logs:*
              - rds:*
              - redshift-serverless:*
              - Redshift:*
              - s3:*
              - secretsmanager:CreateSecret
              - secretsmanager:DeleteSecret
              - secretsmanager:GetSecretValue
              - secretsmanager:ListSecrets
              - secretsmanager:TagResource
              - sqlworkbench:*
              - tag:GetResources
              - tag:GetTagKeys
              - tag:GetTagValues 
            Resource: '*' 
  NVWAWSUAT:
    Type: 'AWS::IAM::Role'
    Properties: 
      Description: CFT Managed via stackset in payer account. NVW AWS UAT Role
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/NVW_AWS_UAT_policy_generic"
        
      AssumeRolePolicyDocument: 
        Statement: 
        - Effect: Allow
          Principal:
            AWS: 
            - arn:aws:iam::782930490923:role/NVW_AWS_UAT             
          Action: 
            - "sts:AssumeRole"  
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/cleardata-boundary'
      RoleName: "NVW_AWS_UAT"
    DependsOn: 
      - NVWAWSUATGeneric